### ISSUE TITLE
Fehler beim Würfelwurf für Fertigkeit List

### ISSUE THREAD

**Issue by Dicuras** [Tealk/roll20-character-sheets#1]
Hallo Tealk,

ich habe mich doch mal bei GitHub angemeldet, da ich noch einen Fehler gefunden habe.

In aborea.html Zeile 267 muss statt der Referenz auf Athletik die Referenz auf List stehen.

Also statt:
`<div><button type="roll" name="roll_list"
 value="@{abilityroll} würfelt List mit dem Ergebnis [[1d10! + @{athletik_attribut} + @{athletik} + ?{Modifier?|0}]]"></button>`

müsste stehen:
`<div><button type="roll" name="roll_list"
 value="@{abilityroll} würfelt List mit dem Ergebnis [[1d10! + @{list_attribut} + @{list} + ?{Modifier?|0}]]"></button>`

Vielen Dank für deine Mühen. 

VG Dicuras

**Comment by Tealk** [comment]
Korrigiert im commit 98534276eb89dcdf61cc16cadd4c2ae6ce3ecc6c
