### ISSUE TITLE
Charakterbogen(Aborea) löscht Daten

### ISSUE THREAD

**Issue by Sharkan92** [Tealk/roll20-character-sheets#4]
Schönen guten Tag,

mit ihrem aktuellen Charakterbogen(Aborea) haben meine Freunde ich aktuell Probleme.
Werte und Daten auf dem Character Sheet(Blatt 2 somit) löschen sich jedes mal nach schließen des Bogens.

Die Werte im Blatt "Attributes & Abilities" verändern sich aber nicht bzw. löschen sich nicht.
Dafür tauchen dort unter Attributes momentan mehre  "undefined" Attribute auf.
Hier ein Bsp: undefined_undefined_st

Im Anhanf befindet Sich die Seite welche die Daten jedes mal löscht.

Vielen Dank im voraus. 

![Problem Bogen](https://user-images.githubusercontent.com/82736358/115129371-80132e80-9fe5-11eb-9828-42a9a64d5f3b.png)

**Comment by Tealk** [comment]
Hi, danke für die Meldung.

Ich habe bereits einen Bugfix auf den Weg gegeben, roll20 muss ihn nur noch online schalten https://github.com/Roll20/roll20-character-sheets/pull/8725

Roll20 hat wohl ein neues System eingeführt was noch nicht so ganz klappt, das kann man hier nachlesen: https://app.roll20.net/forum/post/9883156/character-sheet-enhancements

**Comment by Sharkan92** [comment]
Herzlichen Dank.

Das ging sehr schnell.

großes Dankeschön

**Comment by Tealk** [comment]
Der Bogen wurde gerade angenommen, kann aber noch bis Morgen dauern bis er in Roll20 verfügbar ist.
